#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <prefix>"
    exit 1
fi

fn=`ls -d ${1}*/ | head -n 1`
echo "@import \"${fn}userChrome.css\"" > userChrome.css
echo "@import \"${fn}userContent.css\"" > userContent.css

